### PR TITLE
 Upgrading technical stack (Angular/Electron/WebdriverIO)

### PR DESCRIPTION
**Pull request by agentcole**
# Pull Request Template

## Description

Upgrading Angular from 14.2.3 to 15.2.1
Upgrading Electron from 20.2.0 to 23.1.1

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aadiene** [comment]
Hi @agentcole, thanks for your contribution.
Still reviewing and will update the status afterwards.

**Comment by aadiene** [comment]
Sorry @agentcole, to improve branch structure I had to delete previous branches.
Be more than welcome to submit PRs for next versions

**Comment by agentcole** [comment]
No problem, happy to hear you've updated the structure. 
I just want to learn want I can do better in the future?
Have you thought about using handle/invoke as well? 
Even would it makes sense? Eg. for using them together with rxjs observables

**Comment by aadiene** [comment]
Im planning to improve features and I will keep in mind your precious ideas. 
Would you be available next weeks to work on those together ?

**Comment by agentcole** [comment]
Yes, I'm available next weeks. Would be great!

**Pull request closed without merging**
